### PR TITLE
Bugfix memoryUsage, add indexes, add priority, add queue name

### PR DESCRIPTION
**Pull request by sgasser**
Remove JobInterface, Bugfix memoryUsage, add indexes, add priority, add queue name

### CODE REVIEW

**Comment by frechina** [comment]
why is not this PR approved? It looks nice

**Comment by eymengunay** [comment]
Hello @frechina ,

As you might have guessed, I haven't been using the bundle for a while. Apparently somehow I've missed this pr.

@sgasser: I'm terribly sorry for missing this. Thank you for putting in your time and effort!

Although 1 year late, I'm merging this.

Sorry again!

**Comment by frechina** [comment]
Good news @eymengunay! And thank you @sgasser for your effort

**Comment by frechina** [comment]
@eymengunay I can't see these changes after running composer update

**Comment by eymengunay** [comment]
@frechina; I have forced an update on packagist, it should work now. Can you confirm?

https://packagist.org/packages/eo/job-queue-bundle

**Comment by frechina** [comment]
@eymengunay worked! thanks

**Pull request merged**
